# ===========================================================================
# File: "Fake_env.tcl"
#                        Created: 2005-12-13 09:25:41
#              Last modification: 2005-12-13 09:25:41
# Author: Bernard Desgraupes
# e-mail: <bdesgraupes@easyconnect.fr>
# www: <http://webperso.easyconnect.fr/bdesgraupes/>
# (c) Copyright: Bernard Desgraupes 2005
# All rights reserved.
# ===========================================================================
# 
# Fake XCode environment variables used by the tests suite

set env(__CF_USER_TEXT_ENCODING) "0x1F5:0:91"
set env(ACTION) "build"
set env(APPLE_INTERNAL_DEVELOPER_DIR) "/AppleInternal/Developer"
set env(APPLE_INTERNAL_DIR) "/AppleInternal"
set env(APPLE_INTERNAL_DOCUMENTATION_DIR) "/AppleInternal/Documentation"
set env(APPLE_INTERNAL_LIBRARY_DIR) "/AppleInternal/Library"
set env(APPLE_INTERNAL_TOOLS) "/AppleInternal/Developer/Tools"
set env(ARCHS) "ppc"
set env(BUILD_COMPONENTS) "headers build"
set env(BUILD_DIR) "/Devel/Current/PListCompiler/TestPlc/build"
set env(BUILD_ROOT) "/Devel/Current/PListCompiler/TestPlc/build"
set env(BUILD_STYLE) "Release"
set env(BUILD_VARIANTS) "normal"
set env(BUILT_PRODUCTS_DIR) "/Devel/Current/PListCompiler/TestPlc/build/Release"
set env(CACHE_ROOT) "/Library/Caches/com.apple.Xcode.501"
set env(CCHROOT) "/Library/Caches/com.apple.Xcode.501"
set env(CHMOD) "/bin/chmod"
set env(CHOWN) "/usr/sbin/chown"
set env(CLASS_FILE_DIR) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build/Release/TestPlc_Target.build/JavaClasses"
set env(CLEAN_PRECOMPS) "YES"
set env(CLONE_HEADERS) "NO"
set env(CodeWarrior) "/CodeWarrior_9.0/CodeWarrior"
set env(CONFIGURATION) "Release"
set env(CONFIGURATION_BUILD_DIR) "/Devel/Current/PListCompiler/TestPlc/build/Release"
set env(CONFIGURATION_TEMP_DIR) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build/Release"
set env(CONTENTS_FOLDER_PATH) "TestPlc.app/Contents"
set env(COPY_PHASE_STRIP) "YES"
set env(COPY_RESOURCES_FROM_STATIC_FRAMEWORKS) "YES"
set env(CP) "/bin/cp"
set env(CURRENT_PROJECT_VERSION) ""
set env(DEBUGGING_SYMBOLS) "YES"
set env(DEPLOYMENT_LOCATION) "NO"
set env(DERIVED_FILE_DIR) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build/Release/TestPlc_Target.build/DerivedSources"
set env(DERIVED_FILES_DIR) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build/Release/TestPlc_Target.build/DerivedSources"
set env(DERIVED_PATHS) ""
set env(DERIVED_SOURCES_DIR) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build/Release/TestPlc_Target.build/DerivedSources"
set env(DEVELOPMENT_LANGUAGE) "English"
set env(DOCUMENTATION_FOLDER_PATH) "/Documentation"
set env(DSTROOT) "/tmp/TestPlc.dst"
set env(DYLIB_COMPATIBILITY_VERSION) ""
set env(DYLIB_CURRENT_VERSION) ""
set env(DYLIB_INSTALL_NAME_BASE) ""
set env(ENABLE_HEADER_DEPENDENCIES) "YES"
set env(EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES) "*.nib *.lproj *.framework *.gch *.xcode (*) CVS .svn"
set env(EXECUTABLE_EXTENSION) ""
set env(EXECUTABLE_FOLDER_PATH) "TestPlc.app/Contents/MacOS"
set env(EXECUTABLE_NAME) "TestPlc"
set env(EXECUTABLE_PATH) "TestPlc.app/Contents/MacOS/TestPlc"
set env(EXECUTABLE_PREFIX) ""
set env(EXECUTABLE_SUFFIX) ""
set env(EXECUTABLE_VARIANT_SUFFIX) ""
set env(EXECUTABLES_FOLDER_PATH) "TestPlc.app/Contents/Executables"
set env(FRAMEWORK_FLAG_PREFIX) "-framework"
set env(FRAMEWORK_SEARCH_PATHS) "/Devel/Current/PListCompiler/TestPlc/build/Release"
set env(FRAMEWORK_VERSION) "A"
set env(FRAMEWORKS_FOLDER_PATH) "TestPlc.app/Contents/Frameworks"
set env(FULL_PRODUCT_NAME) "TestPlc.app"
set env(GCC_AUTO_PCH_HEADER_c) ""
set env(GCC_AUTO_PCH_HEADER_c++) ""
set env(GCC_AUTO_PCH_HEADER_objective-c) ""
set env(GCC_AUTO_PCH_HEADER_objective-c++) ""
set env(GCC_DYNAMIC_NO_PIC) "YES"
set env(GCC_ENABLE_AUTO_PCH) "NO"
set env(GCC_ENABLE_FIX_AND_CONTINUE) "NO"
set env(GCC_GENERATE_DEBUGGING_SYMBOLS) "NO"
set env(GCC_PFE_FILE_C_DIALECTS) "c objective-c c++ objective-c++"
set env(GCC_PRECOMPILE_PREFIX_HEADER) "YES"
set env(GCC_PREFIX_HEADER) "TestPlc_Prefix.pch"
set env(GCC_SYMBOLS_PRIVATE_EXTERN) "YES"
set env(GCC_TREAT_WARNINGS_AS_ERRORS) "NO"
set env(GCC_USE_GCC3_PFE_SUPPORT) ""
set env(GCC_VERSION) "4.0"
set env(GCC_WARN_ABOUT_RETURN_TYPE) "YES"
set env(GCC_WARN_UNUSED_VARIABLE) "YES"
set env(GENERATE_PKGINFO_FILE) "YES"
set env(GENERATE_PROFILING_CODE) "NO"
set env(GLOBAL_CFLAGS) ""
set env(GROUP) "bernardo"
# -------------------------------------------------------------
# Redefined for the 'include<>' test
set env(HEADER_SEARCH_PATHS) "$testdir/include"
# -------------------------------------------------------------
set env(HEADERMAP_INCLUDES_PROJECT_HEADERS) "YES"
set env(HOME) "/Users/bernardo"
set env(INCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES) ""
set env(INFOPLIST_FILE) "Info.plist"
set env(INFOPLIST_PATH) "TestPlc.app/Contents/Info.plist"
set env(INFOSTRINGS_PATH) "/InfoPlist.strings"
set env(INIT_ROUTINE) ""
set env(INSTALL_DIR) "/tmp/TestPlc.dst/Users/bernardo/Applications"
set env(INSTALL_GROUP) "bernardo"
set env(INSTALL_MODE_FLAG) "a-w,a+rX"
set env(INSTALL_OWNER) "bernardo"
set env(INSTALL_PATH) "/Users/bernardo/Applications"
set env(INSTALL_ROOT) "/tmp/TestPlc.dst"
set env(JAVA_APP_STUB) "/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub"
set env(JAVA_ARCHIVE_CLASSES) "YES"
set env(JAVA_ARCHIVE_TYPE) "JAR"
set env(JAVA_COMPILER) "/usr/bin/javac"
set env(JAVA_FOLDER_PATH) "TestPlc.app/Contents/Resources/Java"
set env(JAVA_FRAMEWORK_JARS) ""
set env(JAVA_FRAMEWORK_RESOURCES_DIRS) "Resources"
set env(JAVA_JAR_FLAGS) "cv"
set env(JAVA_SOURCE_SUBDIR) "."
set env(JAVA_USE_DEPENDENCIES) "YES"
set env(JAVA_ZIP_FLAGS) "-urg"
set env(JAVAC_DEFAULT_FLAGS) "-J-Xms64m -J-XX:NewSize                                                                                                                   = 4M -J-Dfile.encoding= UTF8"
set env(JIKES_DEFAULT_FLAGS) "+E +OLDCSO"
set env(LD_FLAGS) ""
set env(LEX) "/usr/bin/lex"
set env(LEXFLAGS) ""
set env(LIBRARY_FLAG_NOSPACE) "YES"
set env(LIBRARY_FLAG_PREFIX) "-l"
set env(LIBRARY_SEARCH_PATHS) "/Devel/Current/PListCompiler/TestPlc/build/Release"
set env(LINK_FILE_LIST_normal_ppc) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build/Release/TestPlc_Target.build/Objects-normal/ppc/TestPlc.LinkFileList"
set env(LINKER_LIBRARY_FLAGS) ""
set env(LOCAL_ADMIN_APPS_DIR) "/Applications/Utilities"
set env(LOCAL_APPS_DIR) "/Applications"
set env(LOCAL_DEVELOPER_DIR) "/Library/Developer"
set env(LOCAL_DEVELOPER_EXECUTABLES_DIR) ""
set env(LOCAL_LIBRARY_DIR) "/Library"
set env(MAC_OS_X_VERSION_MAX_ALLOWED) ""
set env(MAC_OS_X_VERSION_MIN_REQUIRED) ""
set env(MACOS_CREATOR) ""
set env(MACOS_CREATOR_ARG) ""
set env(MACOS_TYPE) ""
set env(MACOS_TYPE_ARG) ""
set env(MACOSX_DEPLOYMENT_TARGET) ""
set env(MoreATSUI) "/Devel/Current/AlphaSrc/Alpha/APIs/More ATSUI"
set env(MoreFiles) "/Devel/Current/AlphaSrc/Alpha/APIs/MoreFiles"
set env(NATIVE_ARCH) "ppc"
set env(NO_COMMON) "YES"
set env(OBJECT_FILE_DIR) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build/Release/TestPlc_Target.build/Objects"
set env(OBJECT_FILE_DIR_normal) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build/Release/TestPlc_Target.build/Objects-normal"
set env(OBJROOT) "/Devel/Current/PListCompiler/TestPlc/build"
set env(OPTIMIZATION_CFLAGS) ""
set env(OPTIMIZATION_LEVEL) "0"
set env(OS) "MACOS"
set env(OSAC) "/usr/bin/osacompile"
set env(OTHER_CFLAGS) ""
set env(OTHER_CPLUSPLUSFLAGS) ""
set env(OTHER_LDFLAGS) ""
set env(OTHER_MIGFLAGS) ""
set env(OTHER_OSAFLAGS) ""
set env(OTHER_PRECOMP_CFLAGS) ""
set env(OTHER_RESMERGERFLAGS) ""
set env(OTHER_REZFLAGS) ""
set env(PACKAGE_TYPE) "com.apple.package-type.wrapper.application"
set env(PASCAL_STRINGS) "YES"
set env(PATH) "/usr/bin:/bin:/usr/sbin:/sbin"
set env(PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES) "/usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Developer/Headers"
set env(PBDEVELOPMENTPLIST_PATH) "TestPlc.app/Contents/pbdevelopment.plist"
set env(PFE_FILE_C_DIALECTS) "c"
set env(PKGINFO_FILE_PATH) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build/Release/TestPlc_Target.build/PkgInfo"
set env(PKGINFO_PATH) "TestPlc.app/Contents/PkgInfo"
set env(PLUGINS_FOLDER_PATH) "TestPlc.app/Contents/PlugIns"
set env(PREBINDING) "NO"
set env(PRECOMP_DESTINATION_DIR) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build/Release/TestPlc_Target.build/PrefixHeaders"
set env(PRECOMPILE_PREFIX_HEADER) ""
set env(PREFIX_CFLAG_BASE) ""
set env(PREFIX_FLAGS) ""
set env(PREFIX_HEADER) ""
set env(PREFIX_REFERENCE) ""
set env(PRIVATE_HEADERS_FOLDER_PATH) "TestPlc.app/Contents/PrivateHeaders"
set env(PRODUCT_NAME) "TestPlc"
set env(PRODUCT_SETTINGS_PATH) "/Devel/Current/PListCompiler/TestPlc/Info.plist"
set env(PRODUCT_TYPE) "com.apple.product-type.application"
set env(PRODUCT_TYPE_CFLAGS) ""
set env(PRODUCT_TYPE_CPLUSPLUSFLAGS) ""
set env(PRODUCT_TYPE_HEADER_SEARCH_PATHS) ""
set env(PROJECT) "TestPlc"
set env(PROJECT_DERIVED_FILE_DIR) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build/DerivedSources"
set env(PROJECT_DIR) "/Devel/Current/PListCompiler/TestPlc"
set env(PROJECT_FILE_PATH) "/Devel/Current/PListCompiler/TestPlc/TestPlc.xcodeproj"
set env(PROJECT_NAME) "TestPlc"
set env(PROJECT_TEMP_DIR) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build"
set env(PUBLIC_HEADERS_FOLDER_PATH) "TestPlc.app/Contents/Headers"
set env(PWD) "/Devel/Current/PListCompiler/TestPlc"
set env(RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS) "YES"
set env(REMOVE_CVS_FROM_RESOURCES) "YES"
set env(REMOVE_SVN_FROM_RESOURCES) "YES"
set env(RETAIN_RAW_BINARIES) ""
set env(REZ_COLLECTOR_DIR) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build/Release/TestPlc_Target.build/ResourceManagerResources"
set env(REZ_OBJECTS_DIR) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build/Release/TestPlc_Target.build/ResourceManagerResources/Objects"
set env(REZ_SEARCH_PATHS) "/Devel/Current/PListCompiler/TestPlc/build/Release"
set env(SCRIPT_INPUT_FILE_COUNT) "0"
set env(SCRIPT_OUTPUT_FILE_COUNT) "0"
set env(SCRIPTS_FOLDER_PATH) "TestPlc.app/Contents/Resources/Scripts"
set env(SDKROOT) ""
set env(SECTORDER_FLAGS) ""
set env(SECURITYSESSIONID) "405d50"
set env(SED) "/usr/bin/sed"
set env(SET_DIR_MODE_OWNER_GROUP) "YES"
set env(SET_FILE_MODE_OWNER_GROUP) "NO"
set env(SHARED_DERIVED_FILE_DIR) "/Devel/Current/PListCompiler/TestPlc/build/Release/DerivedSources"
set env(SHARED_FRAMEWORKS_FOLDER_PATH) "TestPlc.app/Contents/SharedFrameworks"
set env(SHARED_PRECOMPS_DIR) "/Library/Caches/com.apple.Xcode.501/SharedPrecompiledHeaders"
set env(SHARED_SUPPORT_FOLDER_PATH) "TestPlc.app/Contents/SharedSupport"
set env(SHELL) "/bin/bash"
set env(SHLVL) "2"
set env(SOURCE_ROOT) "/Devel/Current/PListCompiler/TestPlc"
set env(SRCROOT) "/Devel/Current/PListCompiler/TestPlc"
set env(STRIP_INSTALLED_PRODUCT) "YES"
set env(STRIPFLAGS) ""
set env(SYMBOL_HEADER) ""
set env(SYMBOL_REPOSITORY) ""
set env(SYMROOT) "/Devel/Current/PListCompiler/TestPlc/build"
set env(SYSTEM_ADMIN_APPS_DIR) "/Applications/Utilities"
set env(SYSTEM_APPS_DIR) "/Applications"
set env(SYSTEM_CORE_SERVICES_DIR) "/System/Library/CoreServices"
set env(SYSTEM_DEMOS_DIR) "/Applications/Extras"
set env(SYSTEM_DEVELOPER_APPS_DIR) "/Developer/Applications"
set env(SYSTEM_DEVELOPER_DEMOS_DIR) "/Developer/Applications/Utilities/Built Examples"
set env(SYSTEM_DEVELOPER_DIR) "/Developer"
set env(SYSTEM_DEVELOPER_DOC_DIR) "/Developer/ADC Reference Library"
set env(SYSTEM_DEVELOPER_EXECUTABLES_DIR) ""
set env(SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR) "/Developer/Applications/Graphics Tools"
set env(SYSTEM_DEVELOPER_JAVA_TOOLS_DIR) "/Developer/Applications/Java Tools"
set env(SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR) "/Developer/Applications/Performance Tools"
set env(SYSTEM_DEVELOPER_RELEASENOTES_DIR) "/Developer/ADC Reference Library/releasenotes"
set env(SYSTEM_DEVELOPER_TOOLS) "/Developer/Tools"
set env(SYSTEM_DEVELOPER_TOOLS_DOC_DIR) "/Developer/ADC Reference Library/documentation/DeveloperTools"
set env(SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR) "/Developer/ADC Reference Library/releasenotes/DeveloperTools"
set env(SYSTEM_DEVELOPER_UTILITIES_DIR) "/Developer/Applications/Utilities"
set env(SYSTEM_DOCUMENTATION_DIR) "/Library/Documentation"
set env(SYSTEM_LIBRARY_DIR) "/System/Library"
set env(SYSTEM_LIBRARY_EXECUTABLES_DIR) ""
set env(TARGET_BUILD_DIR) "/Devel/Current/PListCompiler/TestPlc/build/Release"
set env(TARGET_NAME) "TestPlc_Target"
set env(TARGET_TEMP_DIR) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build/Release/TestPlc_Target.build"
set env(TARGETNAME) "TestPlc_Target"
set env(TEMP_DIR) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build/Release/TestPlc_Target.build"
set env(TEMP_FILE_DIR) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build/Release/TestPlc_Target.build"
set env(TEMP_FILES_DIR) "/Devel/Current/PListCompiler/TestPlc/build/TestPlc.build/Release/TestPlc_Target.build"
set env(TEMP_ROOT) "/Devel/Current/PListCompiler/TestPlc/build"
set env(UID) "501"
set env(UNLOCALIZED_RESOURCES_FOLDER_PATH) "TestPlc.app/Contents/Resources"
set env(UNSTRIPPED_PRODUCT) "NO"
set env(USE_DYNAMIC_NO_PIC) "YES"
set env(USE_GCC3_PFE_SUPPORT) ""
set env(USER) "bernardo"
set env(USER_APPS_DIR) "/Users/bernardo/Applications"
set env(USER_LIBRARY_DIR) "/Users/bernardo/Library"
set env(VALID_ARCHS) "m68k i386 sparc hppa ppc ppc7400 ppc970 ppc64"
set env(VERBOSE_PBXCP) "NO"
set env(VERSION_INFO_BUILDER) "bernardo"
set env(VERSION_INFO_EXPORT_DECL) ""
set env(VERSION_INFO_PREFIX) ""
set env(VERSION_INFO_STRING) "@(#)PROGRAM:TestPlc  PROJECT:TestPlc-  DEVELOPER:bernardo  BUILT:\" __DATE__  \" \" __TIME__ \""
set env(VERSION_INFO_SUFFIX) ""
set env(VERSIONING_STUB) ""
set env(VERSIONING_SYSTEM) ""
set env(VERSIONPLIST_PATH) "TestPlc.app/Contents/version.plist"
set env(WARNING_LDFLAGS) ""
set env(Waste) "/CodeWarrior_9.0/CodeWarrior/MacOS Support/(Third Party Support)/WASTE_2.1b1"
set env(WRAPPER_EXTENSION) "app"
set env(WRAPPER_NAME) "TestPlc.app"
set env(WRAPPER_PREFIX) ""
set env(WRAPPER_SUFFIX) ".app"
set env(XCODE_APP_SUPPORT_DIR) "/Library/Application Support/Apple/Developer Tools"
set env(YACC) "/usr/bin/yacc"
set env(YACCFLAGS) ""
set env(ZERO_LINK) "NO"
